[package]
name = "punchline-back"
version = "0.1.0"
authors = ["Konstantin Yakushin <y231966mdk@gmail.com>"]

[dependencies]
rocket = "0.3.6"
rocket_codegen = "0.3.6"
diesel = { version = "1.0.0", features = ["postgres"] }
dotenv = "0.10.1"